### PR TITLE
fixed dict problems

### PR DESCRIPTION
**Pull request by Kyu**

### CODE REVIEW

**Comment by svanikss** [comment]
Seems good, I'll let you know if there are any issues with it.

**Comment by svanikss** [comment]
Hey so I was looking to the logs and I found an error that pops up and it keeps on spamming the user with the message.

`Traceback (most recent call last):
  File "/home/pi/Desktop/FlairYourPostBot.py", line 160, in main
    submission.remove()
  File "<decorator-gen-161>", line 2, in remove
  File "/usr/local/lib/python3.4/dist-packages/praw/decorators.py", line 271, in wrap
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/objects.py", line 274, in remove
    response = self.reddit_session.request_json(url, data=data)
  File "<decorator-gen-8>", line 2, in request_json
  File "/usr/local/lib/python3.4/dist-packages/praw/decorators.py", line 116, in raise_api_exceptions
    return_value = function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 622, in request_json
    retry_on_error=retry_on_error)
  File "/usr/local/lib/python3.4/dist-packages/praw/__init__.py", line 454, in _request
    _raise_response_exceptions(response)
  File "/usr/local/lib/python3.4/dist-packages/praw/internal.py", line 208, in _raise_response_exceptions
    raise Forbidden(_raw=response)
praw.errors.Forbidden: HTTP error
 
Forbidden: HTTP error`

Do you know what could be causing this?

**Comment by Kyu** [comment]
I'm guessing it doesn't have post removal perms in some subreddit? @kooldawgstar

**Comment by svanikss** [comment]
Yeah some of the subs don't have that permissions, I'll message the mods to fix it.

**Pull request merged**
