### PR TITLE
Fixed recursion error, added flair req feature

### PR DESCRIPTION
**Pull request by Kyu**
The flair req feature is a feature where the user responds to the bot with the flair they want and if it's availible in the subreddit, it gives the post that flair

### CODE REVIEW

**Comment by svanikss** [comment]
Hey so when I compile the code from the previous commit that you made it tells me that there is an error with the yield parameter. Will this fix that?

**Comment by Kyu** [comment]
Oops didn't see this. This runs in uses python 3.4 btw

**Comment by svanikss** [comment]
Hey so I am running the code on Python 3.4.2 and I get AttributeError: 'module' object has no attribute 'ensure_future' Do you know what the cause of this could be?

**Comment by Kyu** [comment]
asyncio.ensure_future was added as a method in 3.4.4, although there is a similar method, asyncio.async, and while I think its depreceated, I can add a way to use that if you want

**Comment by svanikss** [comment]
Yeah that would probably work, thanks for all of your help!

**Pull request merged**
